In [ ]:
# -*- coding: utf-8
# Abraji (https://www.abraji.org.br)
# Reinaldo Chaves (reinaldo@abraji.org.br)
# Programa para captar informaçoes gerais dos políticos dos Brasil desde 2006 que o TSE fornece
# Para uso de pesquisas do Publique-se pego apenas a primeira menção de cada CPF
#

In [1]:
import pandas as pd
from pathlib import Path

Fonte: http://www.tse.jus.br/eleicoes/estatisticas/repositorio-de-dados-eleitorais-1/repositorio-de-dados-eleitorais

In [ ]:
# Funcao para ler os arquivos do ano de 2006

In [2]:
def _reader_2006(fname):
    return pd.read_csv(fname, \
                       sep=';', \
                       encoding='latin_1', \
                       names = ['DATA_GERACAO', 
                                'HORA_GERACAO', 
                                'ANO_ELEICAO', 
                                'NUM_TURNO', 
                                'DESCRICAO_ELEICAO', 
                                'SIGLA_UF',
                                'SIGLA_UE',
                                'DESCRICAO_UE',
                                'CODIGO_CARGO',
                                'DESCRICAO_CARGO',
                                'NOME_CANDIDATO',
                                'SEQUENCIAL_CANDIDATO',
                                'NUMERO_CANDIDATO',
                                'CPF_CANDIDATO',
                                'NOME_URNA_CANDIDATO',
                                'COD_SITUACAO_CANDIDATURA',
                                'DES_SITUACAO_CANDIDATURA',
                                'NUMERO_PARTIDO',
                                'SIGLA_PARTIDO',
                                'NOME_PARTIDO',
                                'CODIGO_LEGENDA',
                                'SIGLA_LEGENDA',
                                'COMPOSICAO_LEGENDA',
                                'NOME_LEGENDA',
                                'CODIGO_OCUPACAO',
                                'DESCRICAO_OCUPACAO',
                                'DATA_NASCIMENTO',
                                'NUM_TITULO_ELEITORAL_CANDIDATO',
                                'IDADE_DATA_ELEICAO',
                                'CODIGO_SEXO',
                                'DESCRICAO_SEXO',
                                'COD_GRAU_INSTRUCAO',
                                'DESCRICAO_GRAU_INSTRUCAO',
                                'CODIGO_ESTADO_CIVIL',
                                'DESCRICAO_ESTADO_CIVIL',
                                'CODIGO_NACIONALIDADE',
                                'DESCRICAO_NACIONALIDADE',
                                'SIGLA_UF_NASCIMENTO',
                                'CODIGO_MUNICIPIO_NASCIMENTO',
                                'NOME_MUNICIPIO_NASCIMENTO',
                                'DESPESA_MAX_CAMPANHA',
                                'COD_SIT_TOT_TURNO',
                                'DESC_SIT_TOT_TURNO'],\
                       header=None,\
                       converters={'CPF_CANDIDATO': lambda x: str(x),
                                   'SEQUENCIAL_CANDIDATO': lambda x: str(x)},\
                       usecols=['CPF_CANDIDATO',
                                'NOME_CANDIDATO',
                                'ANO_ELEICAO',
                                'SEQUENCIAL_CANDIDATO',
                                'DESCRICAO_CARGO',
                                'SIGLA_UF'])

Candidatos 2006

In [3]:
folder = Path("dados_politicos/consulta_cand_2006")
candidatos_2006 = pd.concat([
    _reader_2006(csv)
    for csv in folder.glob("*.txt")
])

In [4]:
candidatos_2006.columns = ['ANO_ELEICAO',
              'SG_UF',
              'DS_CARGO',
              'NM_CANDIDATO',
              'SQ_CANDIDATO',
              'NR_CPF_CANDIDATO']

candidatos_2006 = candidatos_2006[['ANO_ELEICAO',
                                   'SG_UF',
                                   'DS_CARGO',
                                   'SQ_CANDIDATO',
                                   'NM_CANDIDATO',
                                   'NR_CPF_CANDIDATO']]

In [5]:
candidatos_2006.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20790 entries, 0 to 888
Data columns (total 6 columns):
ANO_ELEICAO         20790 non-null int64
SG_UF               20790 non-null object
DS_CARGO            20790 non-null object
SQ_CANDIDATO        20790 non-null object
NM_CANDIDATO        20790 non-null object
NR_CPF_CANDIDATO    20790 non-null object
dtypes: int64(1), object(5)
memory usage: 1.1+ MB

In [6]:
candidatos_2006.reset_index().head()

,index,ANO_ELEICAO,SG_UF,DS_CARGO,SQ_CANDIDATO,NM_CANDIDATO,NR_CPF_CANDIDATO
0,0,2006,MT,GOVERNADOR,10190,ANTERO PAES DE BARROS NETO,10342931172
1,1,2006,MT,GOVERNADOR,10340,BENTO SOUZA PORTO,00401897168
2,2,2006,MT,GOVERNADOR,10323,BLAIRO BORGES MAGGI,24204404987
3,3,2006,MT,GOVERNADOR,10153,JOSMAR OLIVEIRA ALDERETE,10392351153
4,4,2006,MT,GOVERNADOR,10000,MAURO CESAR LARA DE BARROS,80200800159

Candidatos 2008

In [7]:
# Até 2010 os campos eram os mesmos, então usa reader_2006

In [8]:
folder = Path("dados_politicos/consulta_cand_2008")
candidatos_2008 = pd.concat([
    _reader_2006(csv)
    for csv in folder.glob("*.txt")
])

In [9]:
candidatos_2008.columns = ['ANO_ELEICAO',
              'SG_UF',
              'DS_CARGO',
              'NM_CANDIDATO',
              'SQ_CANDIDATO',
              'NR_CPF_CANDIDATO']

candidatos_2008 = candidatos_2008[['ANO_ELEICAO',
                                   'SG_UF',
                                   'DS_CARGO',
                                   'SQ_CANDIDATO',
                                   'NM_CANDIDATO',
                                   'NR_CPF_CANDIDATO']]

In [10]:
candidatos_2008.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 384532 entries, 0 to 6935
Data columns (total 6 columns):
ANO_ELEICAO         384532 non-null int64
SG_UF               384532 non-null object
DS_CARGO            384532 non-null object
SQ_CANDIDATO        384532 non-null object
NM_CANDIDATO        384532 non-null object
NR_CPF_CANDIDATO    384532 non-null object
dtypes: int64(1), object(5)
memory usage: 20.5+ MB

In [11]:
candidatos_2008.reset_index().head()

,index,ANO_ELEICAO,SG_UF,DS_CARGO,SQ_CANDIDATO,NM_CANDIDATO,NR_CPF_CANDIDATO
0,0,2008,MG,PREFEITO,41944,CATIA MARIA DE AGUIAR LEMES,30695481649
1,1,2008,MG,PREFEITO,46012,NILSON AMADO DOS SANTOS,49886690682
2,2,2008,MG,VICE-PREFEITO,41945,FREDERICO TEODORO MARRA,04714070622
3,3,2008,MG,VICE-PREFEITO,46013,OLIMPIO GOMES NETO,44102950630
4,4,2008,MG,VEREADOR,43024,ALTINO RODRIGUES,07653035825

Candidatos 2010

In [12]:
# Até 2010 os campos eram os mesmos, então usa reader_2006

In [13]:
folder = Path("dados_politicos/consulta_cand_2010")
candidatos_2010 = pd.concat([
    _reader_2006(csv)
    for csv in folder.glob("*.txt")
])

In [14]:
candidatos_2010.columns = ['ANO_ELEICAO',
              'SG_UF',
              'DS_CARGO',
              'NM_CANDIDATO',
              'SQ_CANDIDATO',
              'NR_CPF_CANDIDATO']

candidatos_2010 = candidatos_2010[['ANO_ELEICAO',
                                   'SG_UF',
                                   'DS_CARGO',
                                   'SQ_CANDIDATO',
                                   'NM_CANDIDATO',
                                   'NR_CPF_CANDIDATO']]

In [15]:
candidatos_2010.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22577 entries, 0 to 855
Data columns (total 6 columns):
ANO_ELEICAO         22577 non-null int64
SG_UF               22577 non-null object
DS_CARGO            22577 non-null object
SQ_CANDIDATO        22577 non-null object
NM_CANDIDATO        22577 non-null object
NR_CPF_CANDIDATO    22577 non-null object
dtypes: int64(1), object(5)
memory usage: 1.2+ MB

In [16]:
candidatos_2010.reset_index().head()

,index,ANO_ELEICAO,SG_UF,DS_CARGO,SQ_CANDIDATO,NM_CANDIDATO,NR_CPF_CANDIDATO
0,0,2010,RR,GOVERNADOR,230000000660,ARIOMAR FARIAS DE LIMA,19952970200
1,1,2010,RR,GOVERNADOR,230000000057,JOSE DE ANCHIETA JUNIOR,32089562315
2,2,2010,RR,GOVERNADOR,230000000504,NEUDO RIBEIRO CAMPOS,02109778253
3,3,2010,RR,GOVERNADOR,230000000082,PETRONIO PEREIRA DE ARAUJO,06356419253
4,4,2010,RR,GOVERNADOR,230000000188,ROBERT DAGON DA SILVA,06524079272

Candidatos 2012

In [17]:
def _reader_2012(fname):
    return pd.read_csv(fname, \
                       sep=';', \
                       encoding='latin_1', \
                       names = ['DATA_GERACAO',
                                'HORA_GERACAO',
                                'ANO_ELEICAO',
                                'NUM_TURNO',
                                'DESCRICAO_ELEICAO', 
                                'SIGLA_UF', 
                                'SIGLA_UE',
                                'DESCRICAO_UE',
                                'CODIGO_CARGO',
                                'DESCRICAO_CARGO',
                                'NOME_CANDIDATO',
                                'SEQUENCIAL_CANDIDATO',
                                'NUMERO_CANDIDATO',
                                'CPF_CANDIDATO',
                                'NOME_URNA_CANDIDATO',
                                'COD_SITUACAO_CANDIDATURA',
                                'DES_SITUACAO_CANDIDATURA', 
                                'NUMERO_PARTIDO', 
                                'SIGLA_PARTIDO', 
                                'NOME_PARTIDO', 
                                'CODIGO_LEGENDA', 
                                'SIGLA_LEGENDA', 
                                'COMPOSICAO_LEGENDA', 
                                'NOME_LEGENDA', 
                                'CODIGO_OCUPACAO', 
                                'DESCRICAO_OCUPACAO', 
                                'DATA_NASCIMENTO', 
                                'NUM_TITULO_ELEITORAL_CANDIDATO', 
                                'IDADE_DATA_ELEICAO', 
                                'CODIGO_SEXO', 
                                'DESCRICAO_SEXO', 
                                'COD_GRAU_INSTRUCAO', 
                                'DESCRICAO_GRAU_INSTRUCAO', 
                                'CODIGO_ESTADO_CIVIL', 
                                'DESCRICAO_ESTADO_CIVIL', 
                                'CODIGO_NACIONALIDADE', 
                                'DESCRICAO_NACIONALIDADE', 
                                'SIGLA_UF_NASCIMENTO', 
                                'CODIGO_MUNICIPIO_NASCIMENTO', 
                                'NOME_MUNICIPIO_NASCIMENTO', 
                                'DESPESA_MAX_CAMPANHA', 
                                'COD_SIT_TOT_TURNO',
                                'DESC_SIT_TOT_TURNO',
                                'E_MAIL'],\
                       header=None,\
                       converters={'CPF_CANDIDATO': lambda x: str(x),
                                   'SEQUENCIAL_CANDIDATO': lambda x: str(x)},\
                       usecols=['CPF_CANDIDATO',
                                'NOME_CANDIDATO',
                                'ANO_ELEICAO',
                                'SEQUENCIAL_CANDIDATO',
                                'DESCRICAO_CARGO',
                                'SIGLA_UF'])

In [18]:
folder = Path("dados_politicos/consulta_cand_2012")
candidatos_2012 = pd.concat([
    _reader_2012(csv)
    for csv in folder.glob("*.txt")
])

In [19]:
candidatos_2012.columns = ['ANO_ELEICAO',
              'SG_UF',
              'DS_CARGO',
              'NM_CANDIDATO',
              'SQ_CANDIDATO',
              'NR_CPF_CANDIDATO']

candidatos_2012 = candidatos_2010[['ANO_ELEICAO',
                                   'SG_UF',
                                   'DS_CARGO',
                                   'SQ_CANDIDATO',
                                   'NM_CANDIDATO',
                                   'NR_CPF_CANDIDATO']]

In [20]:
candidatos_2012.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22577 entries, 0 to 855
Data columns (total 6 columns):
ANO_ELEICAO         22577 non-null int64
SG_UF               22577 non-null object
DS_CARGO            22577 non-null object
SQ_CANDIDATO        22577 non-null object
NM_CANDIDATO        22577 non-null object
NR_CPF_CANDIDATO    22577 non-null object
dtypes: int64(1), object(5)
memory usage: 1.2+ MB

In [21]:
candidatos_2012.reset_index().head()

,index,ANO_ELEICAO,SG_UF,DS_CARGO,SQ_CANDIDATO,NM_CANDIDATO,NR_CPF_CANDIDATO
0,0,2010,RR,GOVERNADOR,230000000660,ARIOMAR FARIAS DE LIMA,19952970200
1,1,2010,RR,GOVERNADOR,230000000057,JOSE DE ANCHIETA JUNIOR,32089562315
2,2,2010,RR,GOVERNADOR,230000000504,NEUDO RIBEIRO CAMPOS,02109778253
3,3,2010,RR,GOVERNADOR,230000000082,PETRONIO PEREIRA DE ARAUJO,06356419253
4,4,2010,RR,GOVERNADOR,230000000188,ROBERT DAGON DA SILVA,06524079272

Candidatos 2014

In [22]:
candidatos_2014 = pd.read_csv("dados_politicos/consulta_cand_2014/consulta_cand_2014_BRASIL.csv",\
                              sep=';', \
                              encoding='latin_1', \
                              converters={'NR_CPF_CANDIDATO': lambda x: str(x),
                                          'SQ_CANDIDATO': lambda x: str(x)},\
                              usecols=['NR_CPF_CANDIDATO',
                                       'NM_CANDIDATO',
                                       'ANO_ELEICAO',
                                       'SQ_CANDIDATO',
                                       'DS_CARGO',
                                       'SG_UF'])

In [23]:
candidatos_2014.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26264 entries, 0 to 26263
Data columns (total 6 columns):
ANO_ELEICAO         26264 non-null int64
SG_UF               26264 non-null object
DS_CARGO            26264 non-null object
SQ_CANDIDATO        26264 non-null object
NM_CANDIDATO        26264 non-null object
NR_CPF_CANDIDATO    26264 non-null object
dtypes: int64(1), object(5)
memory usage: 1.2+ MB

In [24]:
candidatos_2014.reset_index().head()

,index,ANO_ELEICAO,SG_UF,DS_CARGO,SQ_CANDIDATO,NM_CANDIDATO,NR_CPF_CANDIDATO
0,0,2014,PR,GOVERNADOR,160000000645,GLEISI HELENA HOFFMANN,67677061915
1,1,2014,AL,DEPUTADO ESTADUAL,20000000414,JOSENILDO VIEIRA DOS SANTOS,05537705869
2,2,2014,RJ,DEPUTADO ESTADUAL,190000001205,JOSÉ SEVERINO PENHA,42289750468
3,3,2014,RJ,DEPUTADO ESTADUAL,190000002250,ANA TERESA SOUZA DE SENNA,77467817720
4,4,2014,RJ,DEPUTADO ESTADUAL,190000001087,MARISELMA COSTA MUNIZ,00333208706

Candidatos 2016

In [25]:
candidatos_2016 = pd.read_csv("dados_politicos/consulta_cand_2016/consulta_cand_2016_BRASIL.csv",\
                              sep=';', \
                              encoding='latin_1', \
                              converters={'NR_CPF_CANDIDATO': lambda x: str(x),
                                          'SQ_CANDIDATO': lambda x: str(x)},\
                              usecols=['NR_CPF_CANDIDATO',
                                       'NM_CANDIDATO',
                                       'ANO_ELEICAO',
                                       'SQ_CANDIDATO',
                                       'DS_CARGO',
                                       'SG_UF'])

In [26]:
candidatos_2016.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 497776 entries, 0 to 497775
Data columns (total 6 columns):
ANO_ELEICAO         497776 non-null int64
SG_UF               497776 non-null object
DS_CARGO            497776 non-null object
SQ_CANDIDATO        497776 non-null object
NM_CANDIDATO        497776 non-null object
NR_CPF_CANDIDATO    497776 non-null object
dtypes: int64(1), object(5)
memory usage: 22.8+ MB

In [27]:
candidatos_2016.reset_index().head()

,index,ANO_ELEICAO,SG_UF,DS_CARGO,SQ_CANDIDATO,NM_CANDIDATO,NR_CPF_CANDIDATO
0,0,2016,PR,VEREADOR,160000026272,JUVELINO DA COSTA GUERRA,24857223821
1,1,2016,RJ,VEREADOR,190000006421,SILVIO GARCIA DOS SANTOS,69919127787
2,2,2016,RJ,VEREADOR,190000004786,MANOEL MESSIAS DE SOUZA LIMA,12187642798
3,3,2016,RS,VEREADOR,210000025619,DARIO RODRIGUES DA SILVA,28537670006
4,4,2016,SC,VEREADOR,240000007423,DANIELA SOUZA BERTI,01970745967

Candidatos 2018

In [ ]:
candidatos_2018 = pd.read_csv("dados_politicos/consulta_cand_2018/consulta_cand_2018_BRASIL.csv",\
                              sep=';', \
                              encoding='latin_1', \
                              converters={'NR_CPF_CANDIDATO': lambda x: str(x),
                                          'SQ_CANDIDATO': lambda x: str(x)},\
                              usecols=['NR_CPF_CANDIDATO',
                                       'NM_CANDIDATO',
                                       'ANO_ELEICAO',
                                       'SQ_CANDIDATO',
                                       'DS_CARGO',
                                       'SG_UF'])

In [29]:
candidatos_2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29145 entries, 0 to 29144
Data columns (total 6 columns):
ANO_ELEICAO         29145 non-null int64
SG_UF               29145 non-null object
DS_CARGO            29145 non-null object
SQ_CANDIDATO        29145 non-null object
NM_CANDIDATO        29145 non-null object
NR_CPF_CANDIDATO    29145 non-null object
dtypes: int64(1), object(5)
memory usage: 1.3+ MB

In [30]:
candidatos_2018.reset_index().head()

,index,ANO_ELEICAO,SG_UF,DS_CARGO,SQ_CANDIDATO,NM_CANDIDATO,NR_CPF_CANDIDATO
0,0,2018,PE,DEPUTADO FEDERAL,170000614162,MARIA VANIA SILVA DE FARIAS,29270286487
1,1,2018,MA,DEPUTADO ESTADUAL,100000614379,EURAMI REIS PEREIRA,10427830397
2,2,2018,MA,DEPUTADO ESTADUAL,100000605369,DEAN FRANKCIGIRLEY ARAUJO COSTA,83049428368
3,3,2018,SC,DEPUTADO ESTADUAL,240000614246,ADRIANO NUNES,88973140906
4,4,2018,CE,DEPUTADO ESTADUAL,60000611903,ALCIONE DUARTE DA SILVA,22171584300

Une todos e excluí duplicados pelo CPF

In [31]:
frames = [candidatos_2006,
          candidatos_2008,
          candidatos_2010,
          candidatos_2012,
          candidatos_2014,
          candidatos_2016,
          candidatos_2018]

In [32]:
candidatos_todos = pd.concat(frames)

In [33]:
candidatos_todos = candidatos_todos.drop_duplicates(['NR_CPF_CANDIDATO'], keep='last')

In [34]:
candidatos_todos.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 826333 entries, 1 to 29144
Data columns (total 6 columns):
ANO_ELEICAO         826333 non-null int64
SG_UF               826333 non-null object
DS_CARGO            826333 non-null object
SQ_CANDIDATO        826333 non-null object
NM_CANDIDATO        826333 non-null object
NR_CPF_CANDIDATO    826333 non-null object
dtypes: int64(1), object(5)
memory usage: 44.1+ MB

In [35]:
candidatos_todos.reset_index().head()

,index,ANO_ELEICAO,SG_UF,DS_CARGO,SQ_CANDIDATO,NM_CANDIDATO,NR_CPF_CANDIDATO
0,1,2006,MT,GOVERNADOR,10340,BENTO SOUZA PORTO,00401897168
1,3,2006,MT,GOVERNADOR,10153,JOSMAR OLIVEIRA ALDERETE,10392351153
2,8,2006,MT,GOVERNADOR,10052,VANILSON RODRIGUES DA SILVA,89660102100
3,9,2006,MT,VICE-GOVERNADOR,10013,ADILSON AZEVEDO DA COSTA,62947664191
4,10,2006,MT,VICE-GOVERNADOR,10119,ADILSON DAMIAO DA SILVA CRUZ,66804841115

In [36]:
candidatos_todos.to_csv('resultados/todos_candidatos_desde_2006.csv', index=False)